### ISSUE TITLE
0.4.6 breaks charms.openstack (AttributeError: 'NoneType' object has no attribute 'relation_name')

### ISSUE THREAD

**Issue by ryan-beisner** [juju-solutions/charms.reactive#105]
#### Built with charms.reactive 0.4.5: Apr 26 (ok):
https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline_amulet_full/openstack/charm-tempest/458466/5/16/index.html

#### Built with charms.reactive 0.4.6: Today (fail):
https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline/openstack/charm-tempest/458466/5/206/index.html

The tempest-0-var-log.tar.bz2  artifact is of interest for both.

**Comment by tvansteenburgh** [comment]
From unit-tempest-0.log:
```
2017-04-28 19:45:29 INFO run-tempest Traceback (most recent call last):
2017-04-28 19:45:29 INFO run-tempest   File "/usr/local/lib/python3.5/dist-packages/charms_openstack/charm.py", line 870, in render_with_interfaces
2017-04-28 19:45:29 INFO run-tempest     charm_instance=self))
2017-04-28 19:45:29 INFO run-tempest TypeError: __init__() got an unexpected keyword argument 'charm_instance'
2017-04-28 19:45:29 INFO run-tempest 
2017-04-28 19:45:29 INFO run-tempest During handling of the above exception, another exception occurred:
2017-04-28 19:45:29 INFO run-tempest 
2017-04-28 19:45:29 INFO run-tempest Traceback (most recent call last):
2017-04-28 19:45:29 INFO run-tempest   File "/var/lib/juju/agents/unit-tempest-0/charm/actions/run-tempest", line 11, in <module>
2017-04-28 19:45:29 INFO run-tempest     tempest.render_configs([identity_int])
2017-04-28 19:45:29 INFO run-tempest   File "lib/charm/openstack/tempest.py", line 38, in render_configs
2017-04-28 19:45:29 INFO run-tempest     TempestCharm.singleton.render_with_interfaces(interfaces_list)
2017-04-28 19:45:29 INFO run-tempest   File "/usr/local/lib/python3.5/dist-packages/charms_openstack/charm.py", line 874, in render_with_interfaces
2017-04-28 19:45:29 INFO run-tempest     adapters_instance=self.adapters_class(interfaces))
2017-04-28 19:45:29 INFO run-tempest   File "lib/charm/openstack/tempest.py", line 359, in __init__
2017-04-28 19:45:29 INFO run-tempest     options=TempestConfigurationAdapter)
2017-04-28 19:45:29 INFO run-tempest   File "/usr/local/lib/python3.5/dist-packages/charms_openstack/adapters.py", line 938, in __init__
2017-04-28 19:45:29 INFO run-tempest     self.add_relations(relations)
2017-04-28 19:45:29 INFO run-tempest   File "/usr/local/lib/python3.5/dist-packages/charms_openstack/adapters.py", line 960, in add_relations
2017-04-28 19:45:29 INFO run-tempest     self.add_relation(relation)
2017-04-28 19:45:29 INFO run-tempest   File "/usr/local/lib/python3.5/dist-packages/charms_openstack/adapters.py", line 967, in add_relation
2017-04-28 19:45:29 INFO run-tempest     adapter_name, adapter = self.make_adapter(relation)
2017-04-28 19:45:29 INFO run-tempest   File "/usr/local/lib/python3.5/dist-packages/charms_openstack/adapters.py", line 980, in make_adapter
2017-04-28 19:45:29 INFO run-tempest     relation_name = relation.relation_name.replace('-', '_')
2017-04-28 19:45:29 INFO run-tempest AttributeError: 'NoneType' object has no attribute 'relation_name'
```

**Comment by stub42** [comment]
The interesting bit will be "/usr/local/lib/python3.5/dist-packages/charms_openstack/charm.py", line 870, which I think is https://github.com/openstack/charms.openstack/blob/master/charms_openstack/charm.py . The adapter, whatever it is, doesn't have a charm_instance parameter. I think someone is going to need to debug-hooks their way through this one, to work out what the adapter is and why it doesn't have a charm_instance argument, before we can confirm this is a charms.reactive issue.

**Comment by stub42** [comment]
Its probably charms.reactive.relations.RelationBase using a real Python3 metaclass, rather than the Python2/Python3 six.with_metaclass() helper. https://github.com/juju-solutions/charms.reactive/commit/abb185febecaa2c982535a4c68b7976a7f475afa

The second traceback seems to be a tempest charm bug, where TempestCharm.singleton.render_with_interfaces is failing when there is no relation yet (quite possibly a race condition).

**Comment by ajkavanagh** [comment]
The 'bug' isn't so much a bug as a change in behaviour that was introduced in this pull request: https://github.com/juju-solutions/charms.reactive/pull/51/files

Essentially, the (new) `charms.reactive.bus.discover()` function links up the interfaces to their class implementations, which in 0.4.6 is done from the `main()` function, whereas, in 0.4.5 and before it was done at module load time.

The tempest (and other OpenStack reactive charms that have actions) action relied on the (previously undocumented) behaviour of charms.reactive.  Anyway, tempest has been patched at https://review.openstack.org/#/c/460708/ in the run_tempest.py file:

```python
#!/usr/bin/env python3
import sys
sys.path.append('lib')

import charm.openstack.tempest as tempest
import charms.reactive as reactive
import charms.reactive.bus as bus
import charmhelpers.core.hookenv as hookenv

# Make sure that reactive is bootstrapped and all the states are setup
# properly
from charms.layer import basic
basic.bootstrap_charm_deps()
basic.init_config_states()

if __name__ == '__main__':
    # charms.reactive 0.4.6 moved the auto discovery of interfaces out of the
    # module load and into the main() function.  Actions don't want to run the
    # main (as we don't want the handlers/hooks to run) so this just finds the
    # interfaces to the '.from_state()' function will get the interface object.
    bus.discover()
    identity_int = reactive.RelationBase.from_state('identity-admin.available')
    if identity_int is None:
        # The interface isn't connected, so we can't do this yet
        hookenv.action_fail(
            "The identity-admin interface is not available - bailing")
    else:
        tempest.render_configs([identity_int])
        tempest.run_test('smoke')
```

I'm not _absolutely_ sure that the `basic.bootstrap_charm-deps()` or `basic.init_config_states()` is needed, but they are in the hook python files and don't _appear_ to do any harm.

So, **is** this still a bug, or just a change in undocumented bahaviour that we/I in the OpenStack team had divined and then used!

**Comment by johnsca** [comment]
0.4.7 has been released to pypi

**Comment by ajkavanagh** [comment]
That was quick!  I'll back out some changes I made to tempest and barbican charms.  I thought it would be rolled into a later release.  Thanks!

**Comment by johnsca** [comment]
This would have broken other charms that were using relations in actions (I'm not sure how common it is), and possibly all bash charms.
