### ISSUE TITLE
Tests fail on Ubuntu 17.10

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/charms.reactive#128]
Tests fail on Ubuntu 17.10.

The order of the bash invocations in `test_full_stack` changed:

```
- ['test_when_any,test_when,test_when_not,test_when_not_all,test_multi,test_only_once']
?                                              ------------------

+ ['test_when_not_all,test_when_any,test_when,test_when_not,test_multi,test_only_once']
?   ++++++++++++++++++
```

This is on Ubuntu 17.10 with python 3.6. Is this because of the new Ubuntu release or am I doing something wrong? I run the tests using make.

```bash
make test
```

# Full error:

```
======================================================================
FAIL: test_full_stack (test_bus.TestReactiveBus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/merlijn/PHD/tengu/charms.reactive/.tox/py3/lib/python3.6/site-packages/mock/mock.py", line 1724, in _inner
    return f(*args, **kw)
  File "/home/merlijn/PHD/tengu/charms.reactive/.tox/py3/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/merlijn/PHD/tengu/charms.reactive/tests/test_bus.py", line 539, in test_full_stack
    self.assertEqual(mPopen.stdout, [','.join(invoked)])
AssertionError: Lists differ: ['test_when_any,test_when,test_when_not,test_when_not[27 chars]nce'] != ['test_when_not_all,test_when_any,test_when,test_when[27 chars]nce']

First differing element 0:
'test_when_any,test_when,test_when_not,test_when_not[26 chars]once'
'test_when_not_all,test_when_any,test_when,test_when[26 chars]once'

- ['test_when_any,test_when,test_when_not,test_when_not_all,test_multi,test_only_once']
?                                              ------------------

+ ['test_when_not_all,test_when_any,test_when,test_when_not,test_multi,test_only_once']
?   ++++++++++++++++++

    """Fail immediately, with the given message."""
>>  raise self.failureException("Lists differ: ['test_when_any,test_when,test_when_not,test_when_not[27 chars]nce'] != ['test_when_not_all,test_when_any,test_when,test_when[27 chars]nce']\n\nFirst differing element 0:\n'test_when_any,test_when,test_when_not,test_when_not[26 chars]once'\n'test_when_not_all,test_when_any,test_when,test_when[26 chars]once'\n\n- ['test_when_any,test_when,test_when_not,test_when_not_all,test_multi,test_only_once']\n?                                              ------------------\n\n+ ['test_when_not_all,test_when_any,test_when,test_when_not,test_multi,test_only_once']\n?   ++++++++++++++++++\n")
    

```

**Comment by johnsca** [comment]
The new order is actually what I would expect, and I'm not sure why it passes on systems earlier than 17.10 except maybe that some odd bash bug has been fixed (the order is coming from the bash code, not the Python code).

That said, the order really shouldn't matter, so we should probably update that test to split the value and compare with `self.assertCountEqual()` instead.
