### ISSUE TITLE
AttributeError: 'JSONUnitDataView' object has no attribute 'data'

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/charms.reactive#146]
Hitting this inside of relation hooks:

```bash
root@ip-172-31-104-218:/var/lib/juju/agents/unit-pdl-api-0/charm# ./hooks/redis-data-relation-joined 
Traceback (most recent call last):
  File "./hooks/redis-data-relation-joined", line 19, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 71, in main
    hookenv._run_atstart()
  File "/usr/local/lib/python3.5/dist-packages/charmhelpers/core/hookenv.py", line 1070, in _run_atstart
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/endpoints.py", line 109, in _startup
    endpoint._manage_flags()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/endpoints.py", line 182, in _manage_flags
    for key, value in unit.received.items():
  File "/usr/lib/python3.5/_collections_abc.py", line 676, in __iter__
    for key in self._mapping:
  File "/usr/lib/python3.5/collections/__init__.py", line 990, in __iter__
    return iter(self.data)
AttributeError: 'JSONUnitDataView' object has no attribute 'data'
```

**Comment by jamesbeedy** [comment]
@johnsca ^ possibly one of the reasons I thought I was using it wrong, but now I'm thinking it isn't me, this looks like a bug.

**Comment by johnsca** [comment]
I updated PR #123 to address this.  Please re-open this if it's still an issue.  Thanks!

**Comment by jamesbeedy** [comment]
@johnsca confirmed fixed, thx
