### ISSUE TITLE
Last update breaks endpoints

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/charms.reactive#161]
It seems something has gone wrong with the last update, our charms crash when we remove a relation.

```
root@juju-4209d8-68:/var/lib/juju/agents/unit-gateway-test-0/charm# hooks/upstream-relation-departed 
Traceback (most recent call last):
  File "hooks/upstream-relation-departed", line 19, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 71, in main
    hookenv._run_atstart()
  File "/usr/local/lib/python3.5/dist-packages/charmhelpers/core/hookenv.py", line 1090, in _run_atstart
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/endpoints.py", line 124, in _startup
    endpoint._manage_departed()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/endpoints.py", line 186, in _manage_departed
    unit = relation.joined_units.pop(hookenv.remote_unit())
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/endpoints.py", line 520, in pop
    return super().pop(self._translate_key(key))
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/endpoints.py", line 502, in _translate_key
    raise KeyError(key)
KeyError: 'ws-echo/0'
```

So, the issue seems to be that, during a departed hook, `relation-list` doesn't return the currently departing unit:

```
root@juju-4209d8-68:/var/lib/juju/agents/unit-gateway-test-0/charm# relation-list --format=json
[]
```

Because of that, `joined_units` doesn't contain anything, so there is nothing to pop.

This is the same regardless of whether its the last unit departing.

**Comment by galgalesh** [comment]
So, the issue seems to be that, during the last departed hook, `relation-list` doesn't return anything:

```
root@juju-4209d8-68:/var/lib/juju/agents/unit-gateway-test-0/charm# relation-list --format=json
[]
```

Because of that, `joined_units` doesn't contain anything, so there is nothing to pop.

**Comment by galgalesh** [comment]
This is very confusing.. `relation-ids` doesn't show the unit, but you can still use the unit's ids in other commands:

```
root@juju-4209d8-70:/var/lib/juju/agents/unit-gateway-test2-0/charm# relation-get private-address t1/1
10.10.138.19
root@juju-4209d8-70:/var/lib/juju/agents/unit-gateway-test2-0/charm# relation-get private-address t1/0
10.10.138.17
root@juju-4209d8-70:/var/lib/juju/agents/unit-gateway-test2-0/charm# relation-ids
upstream:194
```

**Comment by galgalesh** [comment]
A fix is to change [`endpoints.py` line 192](https://github.com/juju-solutions/charms.reactive/blob/master/charms/reactive/endpoints.py#L192) to

```
        unit = RelatedUnit(relation, hookenv.remote_unit())
```
