### ISSUE TITLE
non-endpoint flags do not work with Endpoint handlers

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#184]
While an argument could be made that the following is poor style, it is surprising that the config_changed handler fails:

```python
class GRPCEndpoint(reactive.Endpoint):
    @when('endpoint.{endpoint_name}.joined')
    def joined(self):
        self.publish()
        reactive.clear_flag(self.expand_name('endpoint.{endpoint_name}.joined'))

    @when('config.changed')
    def config_changed(self):
        self.publish()

    def publish(self):
        config = hookenv.config()
        for rel in self.relations:
            rel.to_publish['target'] = config['target']
            rel.to_publish['ca'] = config['ca']
            rel.to_publish['timeout'] = config['timeout']
```

The traceback would not help people diagnose the problem:

```
Traceback (most recent call last):
  File ".../.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 72, in main
    bus.dispatch(restricted=restricted_mode)
  File ".../.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 382, in dispatch
    _invoke(other_handlers)
  File ".../.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 358, in _invoke
    handler.invoke()
  File ".../.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 180, in invoke
    self._action(*args)
TypeError: config_changed() missing 1 required positional argument: 'self'
```

Work around is to do things as intended, providing methods of the endpoint to publish data and driving it from a normal handler in the main charm.

**Comment by johnsca** [comment]
Odd, I would have expected this to work.  There must be a bug in [_is_endpoint_method](https://github.com/juju-solutions/charms.reactive/blob/master/charms/reactive/decorators.py#L297-L310) as that certainly should be returning `True` for that case.

**Comment by gabrielcocenza** [comment]
It also happened this issue with me. @johnsca the problem is exactly at [has_endpoint_class](https://github.com/juju-solutions/charms.reactive/blob/master/charms/reactive/decorators.py#L308).

If you start the class like this:
`class GRPCEndpoint(reactive.Endpoint):`
the `__globals__` will just find [module 'charms.reactive](https://pastebin.canonical.com/p/DxBw74xkdW/)

If you use:
`class GRPCEndpoint(Endpoint):`
the `__globals__`  is able to find [<class 'charms.reactive.endpoints.Endpoint'>](https://pastebin.canonical.com/p/5S5v3VYFPy/) and it's able to add `args` to the endpoint handler.

I think a workaround for this issue can be to also pass the parameter `desired_flags` to the function `_is_endpoint_method `. This way we could split the flag with the char `.` and check if it has `endpoint` in the first position. E.g: `'endpoint.{endpoint_name}.departed'`, because all endpoints will start with `endpoint` in the `when` family flag

What do you think?
