### ISSUE TITLE
relation hooks without RelationBase

### ISSUE THREAD

**Issue by stub42** [juju-solutions/charms.reactive#48]
Migrating code from pre-reactive means relation hooks without a RelationBase.

A hook definition like this works:

``` python
@hook('{interface:nrpe-external-master}-relation-changed',
      '{interface:local-monitors}-relation-changed')
def enable_nagios():
    [...]
```

But this fails, with an exception about hooks/relations/foo/provides.py not existing:

``` python
@hook('{interface:block-storage}-relation-changed')
def handle_storage():
   [..]
```

I'm not sure why. Hypen in the interface name?

```
Traceback (most recent call last):
  File "hooks/data-relation-changed", line 65, in <module>
    default_hook()
  File "hooks/data-relation-changed", line 56, in default_hook
    main()
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/__init__.py", line 67, in main
    bus.dispatch()
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/bus.py", line 397, in dispatch
    _invoke(hook_handlers)
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/bus.py", line 388, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/bus.py", line 268, in invoke
    args = self._get_args()
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/bus.py", line 262, in _get_args
    return list(chain.from_iterable(self._args))
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/decorators.py", line 58, in arg_gen
    rel = RelationBase.from_name(hookenv.relation_type())
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/relations.py", line 190, in from_name
    relation_class = cls._find_impl(role, interface)
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/relations.py", line 207, in _find_impl
    module = _load_module(filepath)
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/bus.py", line 442, in _load_module
    sys.modules[modname] = load_source(modname, realpath)
  File "/var/lib/juju/agents/unit-postgresql-14/charm/lib/pypi/charms/reactive/bus.py", line 35, in load_source
    return SourceFileLoader(modname, realpath).load_module()
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1571, in get_code
  File "<frozen importlib._bootstrap>", line 1623, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/juju/agents/unit-postgresql-14/charm/hooks/relations/block-storage/provides.py'
```

**Comment by stub42** [comment]
Or confusion with a storage hook, since the interface has -storage in its name?

**Comment by johnsca** [comment]
Firstly, I don't think we ever expected that anyone would convert a charm to layers + reactive and not create the appropriate interface layers.  That would be my recommendation, since you're going to want them eventually anyway.

Secondly, it seems we're watching for `ImportError` but a `FileNotFoundError` is being raised.  That could be a behavior change from py2 to py3.  Regardless, I think this is another case, like #31 and #33, where we need to figure out how to switch to using more complete and standard `import_module` instead of `load_source`.  I think this will actually be easier now that we're on py3, since it supports non-`__init__.py`-containing directories on the path for namespace packages.
