### ISSUE TITLE
install hook failure on Ubuntu Xenial

### ISSUE THREAD

**Issue by javacruft** [juju-solutions/charms.reactive#59]
Xenial appears to not have python3-setuptools installed by default; as a result, layered charms fail to install:

```
2016-03-10 11:11:07 INFO install 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2016-03-10 11:11:09 INFO install Ignoring indexes: https://pypi.python.org/simple
2016-03-10 11:11:09 INFO install Requirement already up-to-date: pip in /usr/lib/python3/dist-packages
2016-03-10 11:11:10 INFO install Ignoring indexes: https://pypi.python.org/simple
2016-03-10 11:11:10 INFO install Processing ./wheelhouse/MarkupSafe-0.23.tar.gz
2016-03-10 11:11:10 INFO install     Complete output from command python setup.py egg_info:
2016-03-10 11:11:10 INFO install     Traceback (most recent call last):
2016-03-10 11:11:10 INFO install       File "<string>", line 1, in <module>
2016-03-10 11:11:10 INFO install     ImportError: No module named 'setuptools'
2016-03-10 11:11:10 INFO install     
2016-03-10 11:11:10 INFO install     ----------------------------------------
2016-03-10 11:11:10 INFO install Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-tisofq7o-build/
2016-03-10 11:11:11 INFO install Traceback (most recent call last):
2016-03-10 11:11:11 INFO install   File "/var/lib/juju/agents/unit-aodh-1/charm/hooks/install", line 8, in <module>
2016-03-10 11:11:11 INFO install     basic.bootstrap_charm_deps()
2016-03-10 11:11:11 INFO install   File "lib/charms/layer/basic.py", line 53, in bootstrap_charm_deps
2016-03-10 11:11:11 INFO install     glob('wheelhouse/*'))
2016-03-10 11:11:11 INFO install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
2016-03-10 11:11:11 INFO install     raise CalledProcessError(retcode, cmd)
2016-03-10 11:11:11 INFO install subprocess.CalledProcessError: Command '['pip3', 'install', '-U', '--no-index', '-f', 'wheelhouse', 'wheelhouse/MarkupSafe-0.23.tar.gz', 'wheelhouse/charmhelpers-0.7.0.tar.gz', 'wheelhouse/pip-7.1.2.tar.gz', 'wheelhouse/netifaces-0.10.4.tar.gz', 'wheelhouse/netaddr-0.7.18.tar.gz', 'wheelhouse/PyYAML-3.11.tar.gz', 'wheelhouse/charms.reactive-0.4.0.tar.gz', 'wheelhouse/Tempita-0.5.2.tar.gz', 'wheelhouse/pyaml-15.8.2.tar.gz', 'wheelhouse/six-1.10.0.tar.gz', 'wheelhouse/Jinja2-2.8.tar.gz']' returned non-zero exit status 1
2016-03-10 11:11:11 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
```

**Comment by javacruft** [comment]
python3-pip on trusty:

$ reverse-depends -r trusty python3-setuptools
Reverse-Depends
===============
[...]
* python3-pip

python3-pip on Xenial does not have the same runtime depends.

**Comment by marcoceppi** [comment]
This is an issue with the base layer

**Comment by marcoceppi** [comment]
This issue was moved to juju-solutions/layer-basic#44
