### ISSUE TITLE
Generated hooks giving traceback

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/charms.reactive#7]
Attempting to run a nodejs layer i wrote: https://github.com/battlemidget/juju-layer-node

None of the maintenance messages are ever printed to the `status-history` and when I log into the machine directly and attempt to run the `hooks/install` script it gives me this error:

```
ubuntu@adam-local-machine-2:/var/lib/juju/agents/unit-node-0/charm$ ./hooks/install 
juju-log: INFO: Reactive main running for hook install
Traceback (most recent call last):
  File "./hooks/install", line 14, in <module>
    main()
  File "lib/charms/reactive/__init__.py", line 54, in main
    bus.discover()
  File "lib/charms/reactive/bus.py", line 425, in discover
    search_path = os.path.join(hookenv.charm_dir(), search_dir)
  File "/usr/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

This is my version of charm tools used to build the resulting charm: `1.7.1-0ubuntu4~ubuntu15.04.1~ppa1`

**Comment by battlemidget** [comment]
Figured it out, doesn't look like you can run the hooks directly unless from juju
